-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION "admin";

-- DROP SEQUENCE public."Bookings_booking_id_seq";

CREATE SEQUENCE public."Bookings_booking_id_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."Halls_hall_id_seq";

CREATE SEQUENCE public."Halls_hall_id_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."Movies_movie_id_seq";

CREATE SEQUENCE public."Movies_movie_id_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."Seats_hall_id_seq";

CREATE SEQUENCE public."Seats_hall_id_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."Seats_seat_id_seq";

CREATE SEQUENCE public."Seats_seat_id_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."Showtimes_showtime_id_seq";

CREATE SEQUENCE public."Showtimes_showtime_id_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."Tickets_ticket_id_seq";

CREATE SEQUENCE public."Tickets_ticket_id_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public."Users_user_id_seq";

CREATE SEQUENCE public."Users_user_id_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;-- public."Halls" определение

-- Drop table

-- DROP TABLE public."Halls";

CREATE TABLE public."Halls" (
	hall_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, -- Уникальный идентификатор зала.
	"name" varchar(50) NOT NULL, -- Название зала.
	capacity int4 NOT NULL, -- Вместимость зала.
	description text NULL, -- Вместимость зала.
	CONSTRAINT "PK_hall_id" PRIMARY KEY (hall_id)
);

-- Column comments

COMMENT ON COLUMN public."Halls".hall_id IS 'Уникальный идентификатор зала.';
COMMENT ON COLUMN public."Halls"."name" IS 'Название зала.';
COMMENT ON COLUMN public."Halls".capacity IS 'Вместимость зала.';
COMMENT ON COLUMN public."Halls".description IS 'Вместимость зала.';


-- public."Movies" определение

-- Drop table

-- DROP TABLE public."Movies";

CREATE TABLE public."Movies" (
	movie_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, -- Уникальный идентификатор фильма.
	title varchar(150) NOT NULL, -- Название фильма.
	genre varchar(50) NOT NULL, -- Жанр фильма.
	duration int4 NOT NULL, -- Длительность в минутах.
	rating varchar(10) NOT NULL, -- Возрастной рейтинг (например, "18+").
	description text NOT NULL, -- Описание фильма.
	CONSTRAINT "PK_movie_id" PRIMARY KEY (movie_id)
);

-- Column comments

COMMENT ON COLUMN public."Movies".movie_id IS 'Уникальный идентификатор фильма.';
COMMENT ON COLUMN public."Movies".title IS 'Название фильма.';
COMMENT ON COLUMN public."Movies".genre IS 'Жанр фильма.';
COMMENT ON COLUMN public."Movies".duration IS 'Длительность в минутах.';
COMMENT ON COLUMN public."Movies".rating IS 'Возрастной рейтинг (например, "18+").';
COMMENT ON COLUMN public."Movies".description IS 'Описание фильма.';


-- public."Users" определение

-- Drop table

-- DROP TABLE public."Users";

CREATE TABLE public."Users" (
	user_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(100) NOT NULL, -- Имя пользователя.
	email varchar(255) NOT NULL, -- Адрес электронной почты, уникальный.
	phone varchar(15) NOT NULL, -- Телефонный номер.
	"password" varchar(255) NOT NULL, -- Пароль.
	"role" text NOT NULL, -- Роль пользователя.
	CONSTRAINT "PK_user_id" PRIMARY KEY (user_id),
	CONSTRAINT "UQ_email" UNIQUE (email)
);

-- Column comments

COMMENT ON COLUMN public."Users"."name" IS 'Имя пользователя.';
COMMENT ON COLUMN public."Users".email IS 'Адрес электронной почты, уникальный.';
COMMENT ON COLUMN public."Users".phone IS 'Телефонный номер.';
COMMENT ON COLUMN public."Users"."password" IS 'Пароль.';
COMMENT ON COLUMN public."Users"."role" IS 'Роль пользователя.';


-- public."Seats" определение

-- Drop table

-- DROP TABLE public."Seats";

CREATE TABLE public."Seats" (
	seat_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, -- Уникальный идентификатор места.
	hall_id bigserial NOT NULL, -- Ссылка на зал.
	"row" int4 NOT NULL, -- Номер ряда.
	"number" int4 NOT NULL, -- Номер в ряду.
	is_vip bool NOT NULL, -- Признак VIP-места.
	CONSTRAINT "PK_seat_id" PRIMARY KEY (seat_id),
	CONSTRAINT "Seats_hall_id_fkey" FOREIGN KEY (hall_id) REFERENCES public."Halls"(hall_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Column comments

COMMENT ON COLUMN public."Seats".seat_id IS 'Уникальный идентификатор места.';
COMMENT ON COLUMN public."Seats".hall_id IS 'Ссылка на зал.';
COMMENT ON COLUMN public."Seats"."row" IS 'Номер ряда.';
COMMENT ON COLUMN public."Seats"."number" IS 'Номер в ряду.';
COMMENT ON COLUMN public."Seats".is_vip IS 'Признак VIP-места.';


-- public."Showtimes" определение

-- Drop table

-- DROP TABLE public."Showtimes";

CREATE TABLE public."Showtimes" (
	showtime_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, -- Уникальный идентификатор сеанса.
	movie_id int8 NOT NULL, -- Ссылка на фильм.
	hall_id int8 NOT NULL, -- Ссылка на зал.
	start_time timestamp NOT NULL,
	end_time timestamp NOT NULL,
	price numeric(10, 2) NOT NULL, -- Цена билета.
	CONSTRAINT "PK_showtime_id" PRIMARY KEY (showtime_id),
	CONSTRAINT "Showtimes_hall_id_fkey" FOREIGN KEY (hall_id) REFERENCES public."Halls"(hall_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT showtimes_movies_fk FOREIGN KEY (movie_id) REFERENCES public."Movies"(movie_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Column comments

COMMENT ON COLUMN public."Showtimes".showtime_id IS 'Уникальный идентификатор сеанса.';
COMMENT ON COLUMN public."Showtimes".movie_id IS 'Ссылка на фильм.';
COMMENT ON COLUMN public."Showtimes".hall_id IS 'Ссылка на зал.';
COMMENT ON COLUMN public."Showtimes".price IS 'Цена билета.';


-- public."Bookings" определение

-- Drop table

-- DROP TABLE public."Bookings";

CREATE TABLE public."Bookings" (
	booking_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, -- Уникальный идентификатор бронирования.
	user_id int8 NOT NULL, -- Ссылка на пользователя.
	showtime_id int8 NOT NULL, -- Ссылка на сеанс.
	booking_time timestamp NOT NULL, -- Время бронирования.
	CONSTRAINT "PK_booking_id" PRIMARY KEY (booking_id),
	CONSTRAINT "Bookings_showtime_id_fkey" FOREIGN KEY (showtime_id) REFERENCES public."Showtimes"(showtime_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT "Bookings_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."Users"(user_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Column comments

COMMENT ON COLUMN public."Bookings".booking_id IS 'Уникальный идентификатор бронирования.';
COMMENT ON COLUMN public."Bookings".user_id IS 'Ссылка на пользователя.';
COMMENT ON COLUMN public."Bookings".showtime_id IS 'Ссылка на сеанс.';
COMMENT ON COLUMN public."Bookings".booking_time IS 'Время бронирования.';


-- public."Tickets" определение

-- Drop table

-- DROP TABLE public."Tickets";

CREATE TABLE public."Tickets" (
	ticket_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, -- Уникальный идентификатор билета.
	booking_id int8 NOT NULL, -- Ссылка на бронирование.
	seat_id int8 NOT NULL, -- Ссылка на место.
	price numeric(10, 2) NULL, -- Цена билета (включая надбавки).
	CONSTRAINT "PK_ticket_id" PRIMARY KEY (ticket_id),
	CONSTRAINT "Tickets_booking_id_fkey" FOREIGN KEY (booking_id) REFERENCES public."Bookings"(booking_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT "Tickets_seat_id_fkey" FOREIGN KEY (seat_id) REFERENCES public."Seats"(seat_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Column comments

COMMENT ON COLUMN public."Tickets".ticket_id IS 'Уникальный идентификатор билета.';
COMMENT ON COLUMN public."Tickets".booking_id IS 'Ссылка на бронирование.';
COMMENT ON COLUMN public."Tickets".seat_id IS 'Ссылка на место.';
COMMENT ON COLUMN public."Tickets".price IS 'Цена билета (включая надбавки).';